### PR TITLE
closes #548 Render emojis in username

### LINKED ISSUE #548: Emoji in usernames not rendered
## Description
New emoji support seems to be working well, thx... but just noticed that emoji in username/handle still don't render.

## How To Reproduce
1. See attached
screen shot 2018-08-20 at 12 25 56

## Your Environment
- Whalebird Version 2.1.0 (41)

### PR DESCRIPTION
**Pull request by h3poteto**

### CODE REVIEW

File: src/renderer/components/TimelineSpace/Contents/Cards/Toot.vue [hunk 1]
```diff
@@ -593,9 +597,14 @@ export default {
         }
       }
 
-      .reblogger-name {
+      .reblogger-name /deep/ {
```
Comment (h3poteto) [inline src/renderer/components/TimelineSpace/Contents/Cards/Toot.vue]: __[stylelint]__ <sub>posted by Sider</sub>

Expected selector ".toot .detail .reblogger .reblogger-name /deep/" to come before selector ".toot .detail .toot-header .user .display-name /deep/" (no-descending-specificity)

File: src/renderer/components/TimelineSpace/Contents/Cards/Toot.vue [hunk 2]
```diff
@@ -593,9 +597,14 @@ export default {
...
         font-size: calc(var(--base-font-size) * 0.86);
         cursor: pointer;
+
+        .emojione {
```
Comment (h3poteto) [inline src/renderer/components/TimelineSpace/Contents/Cards/Toot.vue]: __[stylelint]__ <sub>posted by Sider</sub>

Expected selector ".toot .detail .reblogger .reblogger-name /deep/ .emojione" to come before selector ".toot .detail .toot-header .user .display-name /deep/ .emojione" (no-descending-specificity)
